run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
    - prealloc
    - gofumpt
    - goimports

linters-settings:
  goimports:
    local-prefixes: github.com/salmonumbrella/roam-cli
  misspell:
    locale: US

issues:
  exclude-use-default: true
  max-issues-per-linter: 50
  max-same-issues: 10
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
