version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
    - prealloc
  settings:
    misspell:
      locale: US
    staticcheck:
      checks:
        - all
        - '-ST1000'
        - '-ST1005'
        - '-QF1003'

formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/salmonumbrella/roam-cli

output:
  formats:
    text:
      print-linter-name: true
      print-issued-lines: true

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
